### ISSUE TITLE
Make grid_spec.nc file path in namelist more generic

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GFDL_atmos_cubed_sphere#32]
The FV3 code has a namelist option to provide a "grid_spec" file which is useful for the regional applications as the grid doesn't have to be computed on the fly this way. However, the way the code is written, it has to be the file INPUT/grid_spec.nc, which means FV3-JEDI cannot regrid a regional grid to another regional grid (i.e. require two different grid spec files on two different paths, one original grid and one target grid). 

These if statements in tools/fv_grid_tools.F90 should be modified so that GFDL_atmos_cubed_sphere can work for any grid_spec file specified in the input.nml and not require it to be either none or INPUT/grid_spec.nc.

I have already done this in https://github.com/JCSDA/GFDL_atmos_cubed_sphere/pull/2/ but we eventually plan to use this fork for FV3-JEDI instead of a JCSDA fork. 

I am open to comments or suggestions but my current solution is:
changing
    else if( trim(grid_file) .NE. 'INPUT/grid_spec.nc') then
to be
    else if( trim(grid_file) .EQ. 'Inline') then

Is this the correct way to make FV3 handle any generic value of grid_spec in the input.nml?

**Comment by junwang-noaa** [comment]
@CoryMartin-NOAA  the code was committed in PR #35, can you close the issue?
