### ISSUE TITLE
Bring dzmin change in GFS.v16 to develop branch

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/GFDL_atmos_cubed_sphere#42]
GFS.v16 crashed a few times in early September when a strong typhoon passed through a small island over Japan. In the past month we have been working with GFDL to diagnose the causes. Different approaches have been tested to stabilize the model. It was found that a change made to model/nh_utils.F90 is the most effective and least intrusive. Its impact on forecast is
small. The adjustments only occur rarely over a small portion of the grids. (From Fanglin)

The code change in nh_utils.F90 needs to be brought back to develop branch. The addition change is to make dz_min a namelist variable (currently hard-coded) to allow applications to choose their own value.

**Comment by climbfuji** [comment]
Thanks @junwang-noaa !

**Comment by tanyasmirnova** [comment]
@junwang-noaa 
I see that dz_min=2. in my code. Did you change it to another value inside the subroutine?

**Comment by junwang-noaa** [comment]
@tanyasmirnova, I changed it to 6 in production/GFS.v16 implementation branch (see [PR#41](https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/41)), it's not in develop branch yet. .

**Comment by tanyasmirnova** [comment]
Thank you, @junwang-noaa.

**Comment by junwang-noaa** [comment]
The code is committed in PR#41, close ticket.
