### ISSUE TITLE
Duplicate use fms_mod, only: read_data in tools/external_ic.F90

### ISSUE THREAD

**Issue by snebuda** [NOAA-EMC/GFDL_atmos_cubed_sphere#45]
FV3/atmos_cubed_sphere/tools/external_ic.F90 has a duplicate statement for 
use fms_mod, only: read_data

When I complied with intel 18.0.3 on UW-Madison S4, the duplicate use statement caused the generic interface for read_data to fail while reading the gfs_ctrl.nc vcoord 2d data field.  It incorrectly used the read_data_3d_new routine.

FATAL from PE     7: fms_io(read_data_3d_new), field vcoord in file INPUT/gfs_ctrl.nc: field size mismatch 1

Removing the duplicate statement and recompiling stopped this fatal error.

**Comment by junwang-noaa** [comment]
@snebuda Thanks for letting us know this error and the fix. I added the fix in [PR#44 ](https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/44). It will be committed to the repository next week.

**Comment by snebuda** [comment]
Great - Thanks Jun!
Sharon

**Comment by climbfuji** [comment]
Thanks, @snebuda - I also pulled the fix from @junwang-noaa into the ufs-release/public-v2 branch hosted at the NOAA-GFDL Github fork. See https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/61.

**Comment by junwang-noaa** [comment]
The code is committed  in PR#44, close issue.
