### ISSUE TITLE
Reduce stdout for large runs

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/GFDL_atmos_cubed_sphere#51]
Routine `get_nggps_ic` in `tools/external_ic.F90` writes a lot of information to `stdout` that slows down the model startup for large numbers of MPI tasks. Every tasks spits out something like
```
5140:  enter get_nggps_ic is= 577 ie= 672 js=   1 je=  96 isd= 574 ied= 675 jsd=  -2 jed=  99
5932:  enter get_nggps_ic is=1153 ie=1248 js=2401 je=2496 isd=1150 ied=1251 jsd=2398 jed=2499
```
We should suppress that and either have only the master task say `enter get_nggps_ic`. Or, if this information is potentially useful, only write out the full details if the model is compiled in DEBUG mode.

**Comment by junwang-noaa** [comment]
@climbfuji Is this still a problem?

**Comment by climbfuji** [comment]
I am not too worried about the unnecessary output, so let's close it as not planned.
