### ISSUE TITLE
Support for PGI in codebase

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/GFDL_atmos_cubed_sphere#52]
In dev/emc, there are still several places that have `#ifdef __PGI` to work around some of the peculiarities for this compiler. We don't use PGI, haven't tested if they are still needed or if the dycore compiles at all with PGI. Should we keep those or remove them?

Side note. We do have similar preprocessor directives for Intel and GNU, most notably because of a confirmed bug in the Intel compiler w.r.t. having to declare pointers in explicit OpenMP shared/private statements (GNU is correct). Intel is aware of this problem, but I don't know when they will fix this and do what GNU does.

**Comment by DusanJovic-NOAA** [comment]
Remove all PGI ifdefs

**Comment by climbfuji** [comment]
@DusanJovic-NOAA What's the status of this?

**Comment by DusanJovic-NOAA** [comment]
Since we are not using/testing PGI compiler my suggestion is to remove all PGI ifdefs.

**Comment by climbfuji** [comment]
@grantfirl FYI

**Comment by junwang-noaa** [comment]
@climbfuji Can we close the issue? Thanks

**Comment by climbfuji** [comment]
Have all the ifdefs been removed?

**Comment by junwang-noaa** [comment]
I assume the code updates will be committed to the GFDL's dev/emc branch as the UFS WM is pointing to that. Maybe you can create an issue on GFDL's dycore repo? Thanks

**Comment by climbfuji** [comment]
I am closing this. If someone is interested in having those ifdefs removed (if there are any left), he or she can open an issue in the GFDL repo.
