### ISSUE TITLE
b4b reproducibility for regional runs when changing the MPI decomposition

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/GFDL_atmos_cubed_sphere#55]
Based on the code review of https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/68 for the ufs-release/public-v2 branch, we should revisit the routine `regional_boundary_update` and make sure that it also fills boundary rows that lie in the haloes (i.e. if this is a west edge, then have the BCs fill in (-2:0) x (jsd:jed) instead of just (-2:0) x (jsc:jec) ; from @lharris4 ).

If we do that, we should be able to remove some calls to `mpp_update_domains` that are currrently following the calls to `regional_boundary_update`.

We also need to check if one of the changes that I made in https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/68 is required for dev/emc, too. Quoting from https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/68:
> The perhaps most confusing change is to move the call to `start_group_halo_update(i_pack(8), u, v, domain, gridtype=DGRID_NE)` to further down in the code in `model/sw_core.F90`, because there is a call to a regional boundary update for `u` and `v` after the original location [for regional runs].

**Comment by climbfuji** [comment]
@BinLiu-NOAA Or others do you know if this is still an issue?

**Comment by BinLiu-NOAA** [comment]
@climbfuji For the regional standalone domain configuration, probably RRFS developers/colleagues know better on this.

As for regional parent with a nest (at least moving nest), I believe the reproducibility when using different MPI layouts and/or threads is still a known issue. If regional standalone configuration is no longer an issue. Maybe we can/should close this issue, instead create a new for the regional static/moving nesting configuration.

**Comment by climbfuji** [comment]
Ok, thanks! Closing this.
