### ISSUE TITLE
Update fms_mixedmode branch to dev/emc 20221017 version

### ISSUE THREAD

**Issue by binli2337** [NOAA-EMC/GFDL_atmos_cubed_sphere#78]
The fms_mixedmode branch will be updated to include the latest changes from the dev/emc branch at NOAA-GFDL/GFDL_atmos_cubed_sphere (20221017 version or #aa42f6e).

**Comment by junwang-noaa** [comment]
The code is committed to GFDL's repo. The issue is closed.
